wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.3
    framework: lightning
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1665509013.665526
    t:
      1:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 63
      - 74
      - 80
      2:
      - 1
      - 5
      - 9
      - 41
      - 53
      - 55
      - 63
      - 74
      - 80
      3:
      - 23
      4: 3.8.10
      5: 0.13.3
      8:
      - 5
